BINARY := termigram

.PHONY: build build-version

build:
	TELEGRAM_APP_ID_BAKED=$(TELEGRAM_APP_ID_BAKED) TELEGRAM_APP_HASH_BAKED=$(TELEGRAM_APP_HASH_BAKED) ./build.sh

build-version:
	VERSION=$(VERSION) BINARY_NAME=$(BINARY) TELEGRAM_APP_ID_BAKED=$(TELEGRAM_APP_ID_BAKED) TELEGRAM_APP_HASH_BAKED=$(TELEGRAM_APP_HASH_BAKED) ./build.sh
